### ISSUE TITLE
Ressource: hapipal.com

### ISSUE THREAD

**Issue by VictorBaudot** [dwyl/learn-hapi#106]
Hello, 
I'm new to Hapi and I found this website [(https://hapipal.com/)](https://hapipal.com/) very useful to get started with Hapi (v17).
You should consider adding it in your ReadMe ;)

**Comment by nelsonic** [comment]
@VictorBaudot thanks for opening this issue! please feel free to create a Pull Request adding the link. 👍

**Comment by nelsonic** [comment]
@VictorBaudot thanks again for opening the issue and PR to add the link. 🥇
