### ISSUE TITLE
My application is 2 way SSL enabled but I want a single route in the app to be 1 way SSL

### ISSUE THREAD

**Issue by arankhem** [dwyl/learn-hapi#110]
I am using below tls object to make my application two way ssl

```js
tls: {
      key: fs.readFileSync(`${process.env.NODE_PATH}/ssl/server.key`, encoding),
      cert: fs.readFileSync(`${process.env.NODE_PATH}/ssl/server.crt`, encoding),
      requestCert: true,
      ca: MyCAs,
      rejectUnauthorized: true,
    }
```
Now my entire application is 2 way ssl but i want my /healthcheck api to be 1 way ssl.

Is it possible. I wnet through documentation, posted in [stackoverflow](https://stackoverflow.com/questions/52560149/how-to-disable-2-way-ssl-for-a-specific-route-in-hapi-js) but did not find a way to do it

**Comment by nelsonic** [comment]
@arankhem the _default_ SSL in Node.js Apps is 1-way.
as you say, your config will force 2-way SSL. 
What are your options for using NGINX as a Proxy to your Node.js Server?
That way you could set the default for `/healthcheck` to be 1-way.
I have not found a way of having the _same_ Node.js App have different SSL modes on distinct routes.

Anyone else following along, see: https://thejimmahknows.com/1-way-vs-2-way-ssl-authentication
and: https://gist.github.com/pcan/e384fcad2a83e3ce20f9a4c33f4a13ae
