### ISSUE TITLE
Not able to register plugin in Hapi

### ISSUE THREAD

**Issue by JSidhu1986** [dwyl/learn-hapi#120]
Hi,

I have created a custom plugin and added my route in it. But when I am registering this plugin in server.register() but on running the app it is giving me following error.
"TypeError: Cannot read property 'name' of undefined" at internals.Server.register

stock-route.ts
`export const stockPriceRoutesPlugin = {
    name: 'stock-price-routes',
    version: '1.0.0',
    register: function (server, options, next) {
        server.route({
            method: 'GET',
            path: '/beta/stock/{symbol}/chart/{period}',
            handler: async (request, reply) => {
              const symbol = request.params.symbol;
              const period = request.params.period;
              const stockPricesForPeriod = await server.methods.stockPrice(symbol, period);
              return reply.response(stockPricesForPeriod);
            }
        });
        next();
    }
};`

main.ts

`import { Server } from 'hapi';

const stockPriceRoutesPlugin = require('../src/app/plugin/stock-routes');

const server = new Server({
  port: 3333,
  host: 'localhost'
});

const start = async function () {
  try {
    await server.register([
      {
        plugin: stockPriceRoutesPlugin
      }
    ]);
    await server.start();
    console.log('Server running on %s', server.info.uri);
  } catch (err) {
    console.log(err);
    process.exit(1);
  }
};
start();`

"hapi": "^18.1.0"

**Comment by nelsonic** [comment]
@JSidhu1986 it appears you have not given your plugin a `name` property.
> Please use appropriate code blocks with syntax highlighting if you want help on GitHub.
> see: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code
e.g:
```ts
export const stockPriceRoutesPlugin = {
    name: 'stock-price-routes',
    version: '1.0.0',
    register: function (server, options, next) {
        server.route({
            method: 'GET',
            path: '/beta/stock/{symbol}/chart/{period}',
            handler: async (request, reply) => {
              const symbol = request.params.symbol;
              const period = request.params.period;
              const stockPricesForPeriod = await server.methods.stockPrice(symbol, period);
              return reply.response(stockPricesForPeriod);
            }
        });
        next();
    }
};
```

**Comment by JSidhu1986** [comment]
@nelsonic name property is already there in my plugin.
