### ISSUE TITLE
Transfer repo to dwyl?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-hapi#20]
I think I'm ready to let go of "control" of this repo...
@iteles what do you think? :wink:

**Comment by iteles** [comment]
Those 120 :star2: certainly look good on your profile :wink: 
There's no rush to do this but sounds like a plan :+1: :blush:

**Comment by nelsonic** [comment]
I will soon have *way* more stars on my "_main_" repos. and the sooner we get **dwyl** on the radar for people learning how to build cool things the better. don't you think...?

**Comment by iteles** [comment]
From a dwyl perspective, absolutely!

**Comment by Charlotteis** [comment]
think this can be closed now :D

**Comment by iteles** [comment]
@Charlotteis There are days when there's just too much going on :wink: 
Thanks for catching this!
