### ISSUE TITLE
Add contents guide?

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-hapi#31]
This tutorial is :boom: awesome :boom: in part because it is so thorough.  
I think a 'contents guide' at the beginning might help so people can not only go to parts they want but also so they have an idea ahead of time of what will be covered (things tend to click better for me that way at least).

**Comment by nelsonic** [comment]
@iteles you have write-access (*owner*) on this repo now so you can add anything. 
***or*** *anyone* else who has a spare 5 mins can add the contents.
https://github.com/dwyl/esta is a good example to use.
