### ISSUE TITLE
Missing Info in Intermediate section

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/learn-hapi#40]
https://github.com/nelsonic/learn-hapi/blame/master/README.md#L124-L160

have we not added `npm init / npm install hapi` beacuse it is part of the intermediate section? Are we expecting the user to know that or is it worth adding it in there?

**Comment by nelsonic** [comment]
It's an oversight only part. Please add. Thanks.

**Comment by nelsonic** [comment]
This was fixed in https://github.com/dwyl/learn-hapi/pull/41
