### ISSUE TITLE
Server Composition using Glue?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-hapi#44]
What are the advantages of using `glue` ? https://github.com/hapijs/glue

**Comment by simon-p-r** [comment]
Makes it easier to compose a comprehensive server with multiple connections and numerous plugins. It also exposes access to the server creation life cycle via pre connections and the pre plugins methods.

**Comment by nelsonic** [comment]
@simon-p-r right, but how many people/teams/projects deploying `hapi` Apps/APIs are *actually* ***using**** `glue`...?
I'm happy to write up a section on `glue` but would like to *gauge* how popular its likely to be... 

There were **190,602 downloads** of `hapi` in the past month:
[![NPM](https://nodei.co/npm/hapi.png?downloads=true&downloadRank=true&stars=true)](https://nodei.co/npm/hapi)

But only **10,933** downloads for `glue` ... that's *fewer than* ***6% of projects*** ...

I'm actually a *big fan* of the declarative style of defining an application in a `manifest.json` file.
But I'm *not* a fan of forcing *beginners* to learn ***another*** thing before they can *contribute* to a project or be productive in their work.

Hence my question: *who* is ***using*** `glue`...?

**Comment by vdeturckheim** [comment]
I make a large use of `glue` in one of my personal project right now. My back-end app is organized in small components (managed through `npm`) such as 'auth', 'team and private messaging', 'db management', ...
My final server is actually only composed of a `manifest.json` and a `package.json`. I compose it with `rejoice` and that's all.
I also use glue in each module to forge a server as I need it for testing purpose.

However I do agree it is not a necessary tool for beginners, except, maybe, to promote the idea of composing a hapi server as a collection of, as independents as possible, modules. 

At the end of the day `glue` is just a way to assemble the pieces of a bigger construction [in a clearer way than through coding it together](https://github.com/hapijs/glue/blob/v3/API.md) (link may die when branch `v3` is merged in `master` in `glue` repo)

**Comment by nelsonic** [comment]
@vdt can you share link to the personal project you are describing, or is it private?

**Comment by vdeturckheim** [comment]
@nelsonic it is actually private (gitlab.com + npm private plan) :/ I'll try to provide examples this week-end in a github repo.

**Comment by nelsonic** [comment]
Ah... GitLab. fair enough. 
if you can that would be sweet. thanks.

**Comment by vdeturckheim** [comment]
I'll do my best ;) It's definitely on my bucket list.

**Comment by vdeturckheim** [comment]
@nelsonic You can take a look at [sticky](https://github.com/vdeturckheim/sticky) and its plugins. Let me know if you have any comments or questions regarding this.

**Comment by indieforger** [comment]
Great question @nelsonic! And thanks a lot for the code example @vdeturckheim.
