### ISSUE TITLE
Tutorial for Catbox-Redis Caching?

### ISSUE THREAD

**Issue by sathishkumarsoundharajan** [dwyl/learn-hapi#48]
Need a good and a detailed explanation of catbox and catbox-redis caching.
1. How to use catbox?
2. How to use catbox-redis?
3. Simple Use case of using catbox-redis?
4. What is the actual use case for policy?

Example:
How can we use it for caching external http responses?

**Comment by jamesdixon** [comment]
+1

**Comment by bboysathish** [comment]
Closing now...

**Comment by n1arash** [comment]
+1

**Comment by mmalaquias1** [comment]
+1
