### ISSUE TITLE
API.md (link to it!)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-hapi#69]
Not linking to the API.md is a _bit_ of an oversight ... https://github.com/hapijs/hapi/blob/master/API.md 😮

**Comment by pinglinh** [comment]
Hi @nelsonic where do you suggest to put this link?

**Comment by nelsonic** [comment]
@pinglinh good _question_!
maybe in the https://github.com/dwyl/learn-hapi#background-reading--watching section as the second bullet-point. 👍

**Comment by pinglinh** [comment]
@nelsonic Great thanks! I will do it now :bowing_woman:
