### ISSUE TITLE
Handling File Uploads with Hapi.js

### ISSUE THREAD

**Issue by newswim** [dwyl/learn-hapi#77]
This was published today on https://Scotch.io

It uses `lokijs` and `typescript`

https://scotch.io/bar-talk/handling-file-uploads-with-hapi-js

**Comment by iteles** [comment]
@newswim Thanks for this.

We're also in the process of expanding our uploading module which is fully tested and has minimal dependencies: https://github.com/dwyl/image-uploads

**Comment by newswim** [comment]
Nice! I will try that out soon, have a very cheeky project in mind that involves adding a 🇸🇪 flag to pictures..
