### ISSUE TITLE
Update tutorial to hapi v17

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-hapi#94]
If anyone has some time or is currently learning hapi and wants to give it a go, this tutorial will need to be updated to reflect the breaking changes introduced by hapi v17 released this week https://github.com/hapijs/hapi/releases/tag/v17.0.0

Only then can #93 be merged in.

**Comment by Danwhy** [comment]
Should we leave a small section of the tutorial around v16?
Maybe just a link to the current state of this repo (https://github.com/dwyl/learn-hapi/tree/b58495ea002a9f3f8af8d183f6004d2b483f4591) would be enough?

**Comment by iteles** [comment]
@danwhy, yes, that would be excellent.
An overview of the key differences would also be useful at this early transition stage.

**Comment by nelsonic** [comment]
@iteles I've had this open in my browser for the past couple of weeks:
+ 17.0.0 Release Notes: https://github.com/hapijs/hapi/issues/3658
+ Review the new v17: https://github.com/hapijs/hapi/issues/3623
+ https://medium.com/netscape/async-iterators-these-promises-are-killing-my-performance-4767df03d85b
+ https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8

I haven't been able to find a _performance_ comparison between Hapi v16 vs. Hapi v17 ... 🔍 
As far as I can tell it's a stylistic update that forces the _entire_ community to re-write their apps. 💄 
Hence _low_ on list of "_priorities_" (_compared to other client work..._) ⬇️

**Comment by sledorze** [comment]
I think the content of this issue is *highly* relevant and shades some lights on how a better execution model.
https://github.com/funfix/funfix/pull/37

**Comment by nelsonic** [comment]
A few dependencies out-of-date: https://david-dm.org/dwyl/learn-hapi
![image](https://user-images.githubusercontent.com/194400/36679143-6a2893ac-1b0a-11e8-8611-ce67d47ac9c7.png)

Going to update them _now_.

**Comment by nelsonic** [comment]
`devDependencies` are up-to-date: https://david-dm.org/dwyl/learn-hapi?type=dev
![image](https://user-images.githubusercontent.com/194400/36679607-839547d0-1b0b-11e8-8bbe-b4529ca40c36.png)
