### ISSUE TITLE
Add temporary banner to note that this tutorial is not yet hapi v17?

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-hapi#95]
Until someone has some time to go through this tutorial and update it to hapi v17 #93 , shall we add a note in the [Learn hapi](https://github.com/dwyl/learn-hapi#learn-hapi-) section of the tutorial to let people know it is yet to be updated and pointing them to https://github.com/dwyl/learn-hapi/issues/94 ?

**Comment by nelsonic** [comment]
@iteles it _might_ be _faster_ to just _learn_ the syntax changes and update the tutorial. 😉

**Comment by brobee** [comment]
any documentation about the syntax changes? It is very strange, I haven't found any v17 related tutorial on the web. Any recommendation?
